site_name: 'SITE TITLE'
site_description: "SITE DESCRIPTION"
site_author: "Rock Solid Knowledge"
copyright: "Copyright &copy; 2019 <a class='font-bold' href='https://www.rocksolidknowledge.com' target='_blank' rel='noopener'>Rock Solid Knowledge</a>"
gtm_key: 'GTM-MDF5JFF'
plugins:
    - search
extra:
    version: 1.1.1